Title: Project

columns:
  - width: 1/2
    sticky: true
    sections:
      header:
        type: fields
        fields:
          header:
            type: writer
            toolbar:
              inline: false
            marks:
              - bold
              - italic
            nodes:
              - heading
              - quote
            headings:
              - 2
              - 3
            help: The Title that appears in the projects list
      gallery:
        label: Media Files
        type: files
        template: media-file
        layout: cards
  - width: 1/2
    sections:
      gralinfo:
        type: fields
        fields:
          edition:
            type: number
            label: Edition Number
            width: 1/3
            help: optional
          artists:
            width: 2/3
            type: multiselect
            options: query
            query: 
              fetch: site.find('artists').children
              text: "{{ page.title }}"
              value: "{{ page.title }}"
          eventinfo:
            label: Text Top
            type: writer
            toolbar:
              inline: false
            headings:
              - 2
              - 3
          moreinfo:
            label: Extra Information
            help: Text to appear only after the "read more" button is pressed
            type: writer
            toolbar:
              inline: false
            headings:
              - 2
              - 3
          textbottom:
            label: Text Bottom
            type: writer
            toolbar:
              inline: false
            headings:
              - 2
              - 3
          issale:
            label: Add to the shop?
            width: 1/2
            type: toggle
            text:
              - "no"
              - "yes"
          price:
            width: 1/2
            type: number
            after: CHF
            when: 
              issale: true